POST http://localhost:8080/devops_starter_war_exploded/api/login

{
"username":"user",
"password": "test123"
}

###
GET http://localhost:8080/devops_starter_war_exploded/api/info/user
x-access-token: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c2VyIiwicm9sZXMiOiJ1c2VyIiwiZXhwIjoxNjUxNTc2ODUzLCJpYXQiOjE2NTE1NzUwNTMsImlzc3VlciI6InNlbWVzdGVyc3RhcnRjb2RlLWRhdDMiLCJ1c2VybmFtZSI6InVzZXIifQ.iTc4cjHqpLqqg5x6dppsmrlemcRfVAf6MK1xK32PeRk

###
POST http://localhost:8080/devops_starter_war_exploded/api/login

{
"username":"admin",
"password": "test123"
}

###
GET http://localhost:8080/devops_starter_war_exploded/api/info/admin
x-access-token: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsInJvbGVzIjoiYWRtaW4iLCJleHAiOjE2NTAzNjUzNzMsImlhdCI6MTY1MDM2MzU3MywiaXNzdWVyIjoic2VtZXN0ZXJzdGFydGNvZGUtZGF0MyIsInVzZXJuYW1lIjoiYWRtaW4ifQ.-gro4bZOxGAOOFgdGYzPMv5uJF2wLhCoJvBiRbmOEKo

###
GET http://localhost:8080/devops_starter_war_exploded/api/xxx/harbour/1

###
POST http://localhost:8080/devops_starter_war_exploded/api/xxx/createboat

{
"brand":"brand4",
"make":"make4",
"name":"name4",
"image":"image4"
}

